
# Các package Docker cần cài
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Danh sach user
docker_users:
  - "{{ ansible_user }}"

# Cau hinh mac dinh cua Docker daemon
docker_daemon_config:
  log-driver: json-file
  log-opts: 
    max-size: "10m"
    max-file: "3"
