# Thư mục lưu GPG Key của Docker
docker_keyring_directory: /etc/apt/keyrings

# File GPG Key
docker_gpg_key: /etc/apt/keyrings/docker.asc

# Docker Repository
docker_repository: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

# Các package Docker cần cài
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Tên service Docker
docker_service: docker