# Package NFS Server
nfs_package: nfs-kernel-server

# Ten dich vu
nfs_service: nfs-kernel-server

# Thu muc chia se
nfs_share_directory: /srv/nfs/shared

# File exports
nfs_exports_file: /etc/exports.d/app.exports

# Quyen truy cap mang noi bo
nfs_allowed_network: 10.10.0.0/23

# Quyen export
nfs_export_options: rw,sync,no_subtree_check