# Package NFS Server
nfs_package: nfs-kernel-server

# Ten dich vu
nfs_service: nfs-kernel-server

# Thu muc chia se
nfs_shared_directory: /srv/nfs/shared

# File exports
nfs_exports_file: /etc/exports

# Chỉ các Web Server được phép mount dữ liệu NFS.
nfs_allowed_clients: "{{ groups['web'] | map('extract', hostvars, 'ansible_host') | list }}"

# Quyen export
nfs_export_options: rw,sync,no_subtree_check
