# Package MariaDB
mariadb_package: mariadb-server

# Ten service
mariadb_service: mariadb

# File cau hinh
mariadb_config_file: /etc/mysql/mariadb.conf.d/99-custom.cnf

# IP nghe
mariadb_bind_address: 0.0.0.0

# Port mac dinh
mariadb_port: 3306

# Thông tin tài khoản ứng dụng; mật khẩu phải được khai báo trong Ansible Vault.
mariadb_application_database: enterprise_app
mariadb_application_user: webapp
mariadb_application_hosts: "{{ groups['web'] | map('extract', hostvars, 'ansible_host') | list }}"
mariadb_application_password: ""
