- name: Configure Docker repository
  import_tasks: repository.yml

- name: Install Docker Engine
  import_tasks: install.yml

- name: Configure Docker Service
  import_tasks: service.yml

- name: Configure Docker User
  import_tasks: users.yml

- name: Configure Docker Daemon
  import_tasks: daemon.yml

- name: Verify Docker Installation
  import_tasks: verify.yml

  