# Khai báo máy chủ Ansible quản lý
[haproxy]
loadbalancer ansible_host=10.10.0.210

[web]
webserver ansible_host=10.10.0.220
webserver2 ansible_host=10.10.0.221

[database]
mariadb ansible_host=10.10.0.230

[storage]
storagenfs ansible_host=10.10.0.240

[monitoring]
monitor ansible_host=10.10.0.250

[all:vars]
ansible_user=hoangnh
# Chỉ định python trên máy đích
ansible_python_interpreter=/usr/bin/python3 
