# Khai báo máy chủ Ansible quản lý
[haproxy]
haproxy ansible_host=10.10.0.210

[web]
web ansible_host=10.10.0.220

[database]
mariadb ansible_host=10.10.0.230

[storage]
storage ansible_host=10.10.0.240

[monitoring]
monitoring ansible_host=10.10.0.250

[all:vars]
ansible_user=hoangnh
# Chỉ định python trên máy đích
ansible_python_interpreter=/usr/bin/python3 
